### ISSUE TITLE
can not work in nuxt !!!!

### ISSUE THREAD

**Issue by dmwin72015** [amcharts/amcharts4#112]
I import amcharts to nuxt 
if use Server rendering ,  prompt syntax error
`export { System, getSystem } from "./.internal/core/System";
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at r (/huobi/nuxt-demo/node_modules/vue-server-renderer/build.js:8330:16)
    at Object.<anonymous> (server-bundle.js:4193:18)
    at __webpack_require__ (webpack:/webpack/bootstrap bc282d3dc2e201dabb64:25:0)
    at Object.105 (components/coins/amkLine.vue?bd33:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap bc282d3dc2e201dabb64:25:0)
    at Object.131 (components/coins/amkLine.vue:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap bc282d3dc2e201dabb64:25:0) statusCode: 500, name: 'SyntaxError' }`

[someone encountered the same error ](https://github.com/nuxt/nuxt.js/issues/3336)

but in Client rendering, everything is ok

**Comment by dmwin72015** [comment]
i have resolve this problem, by [https://github.com/nuxt/nuxt.js/issues/3336](https://github.com/nuxt/nuxt.js/issues/3336)

**Comment by martynasma** [comment]
@dmwin72015 Thanks for sharing your solution!

**Comment by martynasma** [comment]
@dmwin72015 You mentioned [this solution](https://github.com/nuxt/nuxt.js/issues/2392#issuecomment-352185750) works as well.

Would you be willing to share your amCharts-related code for that solution?

I'd love to post this on our docs website, with your permission.

**Comment by phox081** [comment]
like said in : https://github.com/nuxt/nuxt.js/issues/2392#issuecomment-414059753

**in nuxt.config.js**
try adding   transpile: ['@amcharts/amcharts4']:

```javascript
/*
   ** Build configuration
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {
      // ...
    },
    transpile: ['@amcharts/amcharts4']
  }
}
```

than you can import **amcharts4** as found in the Docs:


```javascript
import * as am4core from '@amcharts/amcharts4/core'
import * as am4charts from '@amcharts/amcharts4/charts'
import am4themes_animated from '@amcharts/amcharts4/themes/animated'
// Themes begin
am4core.useTheme(am4themes_animated)
...
```
