### ISSUE TITLE
SVGPathElement is not defined

### ISSUE THREAD

**Issue by Clientik** [amcharts/amcharts4#1387]
Hello. Why an error occurs in amcharts 4 when conducting unit tests.
I am using Vue-Cli 3. mocha-webpack (unit test)
```
 1) Компонент Krs
       renders props.msg when passed:
     ReferenceError: SVGPathElement is not defined
      at Sprite../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js.Sprite.setPath (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\Sprite.js:6436:1)
      at Sprite.set [as path] (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\Sprite.js:6426:1)
      at new ZoomOutButton (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\elements\ZoomOutButton.js:56:1)
      at Container../node_modules/@amcharts/amcharts4/.internal/core/Container.js.Container.createChild (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\Container.js:466:1)
      at new XYChart (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\charts\types\XYChart.js:273:1)
      at Container../node_modules/@amcharts/amcharts4/.internal/core/Container.js.Container.createChild (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\Container.js:466:1)
      at createChild (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\utils\Instance.js:60:1)
      at Module.create (dist\webpack:\node_modules\@amcharts\amcharts4\.internal\core\utils\Instance.js:172:1)
      at VueComponent.createchart (dist\webpack:\Krs.vue:96:1)
      at VueComponent.mounted (dist\webpack:\Krs.vue:238:1)
      at invokeWithErrorHandling (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:1854:1)
      at callHook (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:4213:1)
      at Object.insert (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:3139:1)
      at invokeInsertHook (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:6340:1)
      at VueComponent.patch [as __patch__] (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:6559:1)
      at VueComponent.Vue._update (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:3939:1)
      at VueComponent.updateComponent (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:4060:1)
      at Watcher.get (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:4473:1)
      at new Watcher (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:4462:1)
      at mountComponent (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:4067:1)
      at VueComponent../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (dist\webpack:\node_modules\vue\dist\vue.runtime.esm.js:8409:1)
      at mount (dist\webpack:\node_modules\@vue\test-utils\dist\vue-test-utils.js:8649:1)
      at Context.it (dist\webpack:\tests\unit\example.spec.js:7:1)

```

**Comment by maneetgoyal** [comment]
Ran into the same issue yesterday while testing with jest. SVGPathElement doesn’t exist on node. It exists on browser.

What you can try is:

Before the test include 

‘’’
window.SVGPathElement = () => {};
‘’’

This way of mocking helped me run the test cases.

**Comment by Clientik** [comment]
> Столкнулся с той же проблемой вчера во время тестирования с шуткой. SVGPathElement не существует на узле. Он существует в браузере.
> 
> Что вы можете попробовать:
> 
> Перед тестом включают
> 
> ‘
> окно.SVGPathElement = () = > {}; >
> ‘’’
> 
> Этот способ издевательства помог мне запустить тестовые случаи.

And where did you insert this code? I inserted it into the mounted block but still displays an error.

**Comment by maneetgoyal** [comment]
@Clientik If a certain function uses `SVGPathElement`, it should be defined just before that. I can give you a Jest example.

Lets say you want to test the following TS function:

```ts
import { Polygon } from "@amcharts/amcharts4/core";

export function generatePolygon(svgString: string): Polygon {
  const polygon = new Polygon();
  polygon.path = svgString;
  return polygon;
}

```
When performing `polygon.path = svgString`, a setter function is triggered which eventually needs `SVGPathElement`.

In the test code, the following can be done:

```js
it("Should test `generatePolygon`, () => {
  Object.assign(window, {SVGPathElement: () => {}});
  const input = "L 1,2 L 2,3 E";
  const output = generatePolygon(input);
  expect(output.path).toBe(input);
});
```

**Comment by Clientik** [comment]
> @Clientik If a certain function uses `SVGPathElement`, it should be defined just before that. I can give you a Jest example.
> 
> Lets say you want to test the following TS function:
> 
> ```ts
> import{ Polygon} from " @amcharts/amcharts4/core";
> 
>  exportfunction generatePolygon(svgString:  string):  Polygon {
>  const polygon =  new Polygon();
>  polygon.path = svgString;
>  return polygon;
> ```
> 
> When performing `polygon.path = svgString`, a setter function is triggered which eventually needs `SVGPathElement`.
> 
> In the test code, the following can be done:
> 
> ```js
> it("Should test `generatePolygon`, () => {
>  Object.assign(window, {SVGPathElement: () => {}});
>  const input = "L 1 , 2  L 2 , 3  E"; 
>  const output = generatePolygon(input);
>  expect(output.path).toBe(input);
> });
> ```
Strange but for some reason this does not work
My test function
```
import { mount } from '@vue/test-utils';
import App from '@/App.vue';

describe('Компонент Krs', () => {
  Object.assign(window, { SVGPathElement: () => {} });
  const wrapper = mount(App);
  // также легко проверить наличие других элементов
  it('имеет кнопку', () => {
    wrapper.find('btn btn-start').trigger('click');
  });
});
```
My generate functions
```
methods: {
    createchart() {
      // eslint-disable-next-line prefer-const
      let chart = am4core.create(this.$refs.chartdiv, am4charts.XYChart);
      chart.paddingRight = 20;
      chart.zoomOutButton.disabled = true;
      chart.dateFormatter.inputDateFormat = 'dd.MM.yyyy';
      const dateAxis = chart.xAxes.push(new am4charts.DateAxis());
      dateAxis.renderer.grid.template.location = 0;
      dateAxis.tooltipDateFormat = 'dd.MM.yyyy';
      const valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
      valueAxis.tooltip.disabled = true;
      valueAxis.renderer.minWidth = 35;
      const series = chart.series.push(new am4charts.LineSeries());
      series.dataFields.valueY = 'value';
      series.dataFields.dateX = 'date';
      series.tooltipText = '{value}';
      series.strokeWidth = 2;
      series.minBulletDistance = 10;
      // Drop-shaped tooltips
      series.tooltip.background.cornerRadius = 20;
      series.tooltip.background.strokeOpacity = 0;
      series.tooltip.pointerOrientation = 'vertical';
      series.tooltip.label.minWidth = 40;
      series.tooltip.label.minHeight = 40;
      series.tooltip.label.textAlign = 'middle';
      series.tooltip.label.textValign = 'middle';

      series.tooltipText = '{valueY.value} руб';
      chart.cursor = new am4charts.XYCursor();

      const scrollbarX = new am4charts.XYChartScrollbar();
      scrollbarX.series.push(series);
      chart.scrollbarX = scrollbarX;
      chart.data = this.cb;
      this.chart = chart;
      let scrollTimer;
      clearTimeout(scrollTimer);
      scrollTimer = setTimeout(() => {
        this.chart.scrollbarX.start = this.resizegraph + 0.000001;
      }, 500); // Задержка для авторесайза
    },
  },
  mounted() {
    this.createchart();
  },
```

**Comment by maneetgoyal** [comment]
What error are you getting? Mocking may not work always.

Here's the line in source code which is probably troubling you: https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/Sprite.ts#L7281

For my case, it solved the issue because my original test didn't care about the outcome of `this.element instanceof SVGPathElement`.

May be try figuring out how can you bring SVGPathElement on node. Or alternately, try running your test on the browser (**jsdom** doesn't have SVGPathElement too.)

Some references:
1. https://github.com/facebook/jest/issues/5379
2. https://github.com/jsdom/jsdom/issues/2128

**Comment by Clientik** [comment]
> What error are you getting? Mocking may not work always. Here's the [line](https://github.com/amcharts/amcharts4/blob/master/src/.internal/core/Sprite.ts#L7281) in source code which is probably troubling you:
> 
> May be try figuring out how can you bring SVGPathElement on node. Or alternately, try running your test on the browser.
> 
> Some references:
> 
> 1. [facebook/jest#5379](https://github.com/facebook/jest/issues/5379)
> 2. [jsdom/jsdom#2128](https://github.com/jsdom/jsdom/issues/2128)

I decided to use Jest, but now the new error rolls.

```
E:\tz-kurs>npm run test:unit

> kurs@0.1.0 test:unit E:\tz-kurs
> vue-cli-service test:unit

 FAIL  tests/unit/Krs.spec.js (13.12s)
  Krs.vue
    × renders correctly (602ms)

  ● Krs.vue › renders correctly

    html container not found

       95 |     createchart() {
       96 |       // eslint-disable-next-line prefer-const
    >  97 |       let chart = am4core.create('chartdiv', am4charts.XYChart);
          | ^
       98 |       chart.paddingRight = 20;
       99 |       chart.zoomOutButton.disabled = true;
      100 |       chart.dateFormatter.inputDateFormat = 'dd.MM.yyyy';

      at createChild (node_modules/src/.internal/core/utils/Instance.ts:156:9)
      at Object.create (node_modules/src/.internal/core/utils/Instance.ts:202:14)
      at VueComponent.createchart (src/components/Krs.vue:97:1)
      at VueComponent.mounted (src/components/Krs.vue:240:1)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
      at callHook (node_modules/vue/dist/vue.runtime.common.dev.js:4201:7)
      at Object.insert (node_modules/vue/dist/vue.runtime.common.dev.js:3133:7)
      at invokeInsertHook (node_modules/vue/dist/vue.runtime.common.dev.js:6320:28)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6537:5)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3927:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4048:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4055:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8386:10)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:21)
      at Object.test (tests/unit/Krs.spec.js:14:21)

  console.log node_modules/@amcharts/amcharts4/.internal/core/System.js:481
    html container not found
```
My test file
```
import { mount } from '@vue/test-utils';
import Krs from '@/components/Krs.vue';


describe('Krs.vue', () => {
  test('renders correctly', () => {
    const wrapper = mount(Krs);
    expect(wrapper.element).toMatchSnapshot();
  });
});

```

**Comment by maneetgoyal** [comment]
Seems like you are referring to some DOM element but the DOM doesn't exist on Node. May be look into: [JSDOM](https://github.com/jsdom/jsdom) or [Pupetter](https://github.com/GoogleChrome/puppeteer).

**Comment by BerritZhang** [comment]
try like this:

import { mount } from '@vue/test-utils';
import Krs from '@/components/Krs.vue';

class SVGPathElement extends HTMLElement {}
window.SVGPathElement = SVGPathElement

describe('Krs.vue', () => {
  test('renders correctly', () => {
    const wrapper = mount(Krs);
    expect(wrapper.element).toMatchSnapshot();
  });
