### ISSUE TITLE
PDf export show this msg "Export operation took longer than expected. Something might have gone wrong"

### ISSUE THREAD

**Issue by Mahisandy** [amcharts/amcharts4#2605]
**Question**

**Environment (if applicable)**

**Additional context**

**Comment by martynasma** [comment]
You may need to increase timeout if you have a complex/large chart:

https://www.amcharts.com/docs/v4/reference/export/#timeoutDelay_property

```
chart.exporting.timeoutDelay = 5000;
```

**Comment by Mahisandy** [comment]
![image](https://user-images.githubusercontent.com/54665162/85030736-72113900-b19b-11ea-90ea-ad0701a443c7.png)
still i am  facing same error 
do u want add some dependent  js reference to add

**Comment by martynasma** [comment]
Do you get any errors in browser console?

**Comment by Mahisandy** [comment]
can you check once this is codepen
https://codepen.io/mahisandy/pen/abdpqjJ

**Comment by xorspark** [comment]
The issue is that you're using a very old version of amCharts which does not support PDF data export. This feature was introduced in 4.7.0 - you're on 4.5.6, which is almost a year old. You should update as we're currently on 4.9.27.

**Comment by Amit6882** [comment]
Hi @martynasma @amcharts Getting the same error.
**Export operation took longer than expected. Something might have gone wrong.** 

**error in console**
polyfills.js:9924 Unhandled Promise rejection: This page contains the following errors:error on line 1 at column 13633: invalid character in attribute value
Below is a rendering of the page up to the first error. ; Zone: <root> ; Task: Promise.then ; Value: Error: This page contains the following errors:error on line 1 at column 13633: invalid character in attribute value
Below is a rendering of the page up to the first error.
    at Parser.checkDocument (:4200/canvg.js:8169)
    at Parser.parseFromString (:4200/canvg.js:8160)
    at Function.fromString (:4200/canvg.js:14360)
    at Export.<anonymous> (vendor.js:177259)
    at step (vendor.js:209545)
    at Object.next (vendor.js:209526)
    at fulfilled (vendor.js:209516)
    at ZoneDelegate.invoke (polyfills.js:9629)
    at Zone.run (polyfills.js:9388)
    at polyfills.js:10122 Error: This page contains the following errors:error on line 1 at column 13633: invalid character in attribute value
Below is a rendering of the page up to the first error.
    at Parser.checkDocument (http://localhost:4200/canvg.js:8169:15)
    at Parser.parseFromString (http://localhost:4200/canvg.js:8160:21)
    at Function.fromString (http://localhost:4200/canvg.js:14360:32)
    at Export.<anonymous> (http://localhost:4200/vendor.js:177259:52)
    at step (http://localhost:4200/vendor.js:209545:23)
    at Object.next (http://localhost:4200/vendor.js:209526:53)
    at fulfilled (http://localhost:4200/vendor.js:209516:58)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:9629:30)
    at Zone.run (http://localhost:4200/polyfills.js:9388:47)
    at http://localhost:4200/polyfills.js:10122:40

**Comment by ganapathyHf** [comment]
I am also facing the same issue as @Amit6882

**Comment by ganapathyHf** [comment]
Found the fix. Our application is an Ember app. In ember-cli-build.js, adding `deps/pdfmake` to amcharts4 > files fixed the issue
