### ISSUE TITLE
next js production build error : ReferenceError: addEventListener is not defined

### ISSUE THREAD

**Issue by rikinshah23** [amcharts/amcharts4#2608]
I am working on nextjs project and using amcharts library. 

When I build production build, it gives me below error. 

```
> Build error occurred
{ ReferenceError: addEventListener is not defined
    at new Registry (D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:4945:9)
    at Module.u55L (D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:5159:16)
    at __webpack_require__ (D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:29:31)
    at Object.11 (D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:334:18)
    at __webpack_require__ (D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:29:31)
    at D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:124:18
    at Object.<anonymous> (D:\XKDashboardClient\.next\server\static\FsJlbi7eD-pYXPY5IEwnp\pages\patientDetails.js:127:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32) type: 'ReferenceError' }
Automatically optimizing pages .npm ERR! code ELIFECYCLE
```

Here is my next.config.js file 

```
const withCSS = require("@zeit/next-css");
const withImages = require("next-images");
const withFonts = require("nextjs-fonts");
const withTM = require("next-transpile-modules")([
  "react-native-vector-icons",
  "@amcharts/amcharts4/core",
  "@amcharts/amcharts4/charts",
  "@amcharts/amcharts4/themes/animated",
]); // pass the modules you would like to see transpiled


module.exports = withCSS(
  withTM(
      withImages(
        withFonts({
          /* config options here */
          env: {
            API_URL: "http://localhost:4000/api/",
            SOCKET_URL: "http://localhost:4000/",
          },
        })
    )
  )
);
```
If I comment out below code then it works and no error. 
this code is from - node_modules\@amcharts\amcharts4\.internal\core\Registry.js

![image](https://user-images.githubusercontent.com/26806597/85058869-f940bb80-b15f-11ea-9681-3ca2c7c81bcc.png)

**Comment by rikinshah23** [comment]
UPDATE: 

I fixed the build error by removing amcharts from webpack file. and import it like below when page loads. 

```
let am4core = null;
let am4charts = null;
let am4themesAnimated = null;
if (process.browser) {
  console.log("process.browser", process.browser);
  am4core = require("@amcharts/amcharts4/core");
  am4charts = require("@amcharts/amcharts4/charts");
  am4themesAnimated = require("@amcharts/amcharts4/themes/animated");
  am4core.useTheme(am4themesAnimated.default);
}
```

Now my prod build works fine and chart is loading fine on first load. 
When I refresh the page it shows me below error: 

```
charts.js:1 Uncaught ReferenceError: am4internal_webpackJsonp is not defined
    at charts.js:1
(anonymous) @ charts.js:1
maps.js:1 Uncaught ReferenceError: am4internal_webpackJsonp is not defined
    at maps.js:1
```

how do I fix this? Your help is appreciated. Thanks

**Comment by rikinshah23** [comment]
@Pauan Thanks for your solution. ([https://github.com/amcharts/amcharts4/issues/272#issuecomment-646326596](https://github.com/amcharts/amcharts4/issues/272#issuecomment-646326596)
