### ISSUE TITLE
Series tooltip issue when wrapping and remaining length is 2 with remaining space 1

### ISSUE THREAD

**Issue by Eldair** [amcharts/amcharts4#3700]
**Bug description**

```
TypeError: Cannot read property 'length' of undefined
  at draw(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/elements/Label.js:512:64)
  at validate(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js:530:14)
  at showTooltip(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/Sprite.js:7968:39)
  at showTooltipAtDataItem(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/charts/series/XYSeries.js:1421:38)
  at showTooltipAtPosition(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/charts/series/XYSeries.js:1344:30)
  at fn(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/charts/types/XYChart.js:1019:36)
  at each(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/utils/Array.js:74:9)
  at each(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/utils/List.js:734:9)
  at showSeriesTooltip(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/charts/types/XYChart.js:1013:21)
  at call(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/charts/types/XYChart.js:850:18)
  at dispatch(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/utils/EventDispatcher.js:380:111)
  at idleQueue(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/utils/EventDispatcher.js:286:38)
  at triggerIdle(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/utils/AsyncPending.js:124:9)
  at update(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/System.js:281:9)
  at apply(webpack://example.test/../../node_modules/@amcharts/amcharts4/.internal/core/System.js:324:23)
```

This issue is caused in cases when excessChars (Label.js:479)/maxChars (Label.js:510) happens to be 1 and chunk.text.length happens to be 2 (Label.js:510) - this then causes splitlines from code below to be an empty array

```
splitLines = $utils.splitTextByCharCount(chunk.text, maxChars, true, this.rtl, false);
// Check if the first word is too long
if ((splitLines[0].length > maxChars) || maxChars === 1) {
    // Yes - move the whole chunk to the next line
    // Remove the element we just added
    lineInfo.element.node.removeChild(lastNode);
    // Break out of the while on next cycle
    excessChars = 0;
}
```

You can see it here when hovering over any value https://codepen.io/Eldair/pen/NWGEvOY

**Comment by martynasma** [comment]
Fixed in [4.10.22](https://github.com/amcharts/amcharts4/releases/tag/4.10.22).

## [4.10.22] - 2021-08-20

### Changed
- `package.json` for ES2015 package was properly updated with new version dependencies.

### Fixed
- Another issue with label text with a lot of in-line formatting not wrapping properly fixed.
- ForceDirectedTree was not updating label `maxWidth` on zoom.
- Legend's `position = "absolute"` was not working.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

[Download options](https://www.amcharts.com/download/).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.
