### ISSUE TITLE
Jest World Map Rendering issue in test cases. (#jest,#react,#react-testing-library)

### ISSUE THREAD

**Issue by ivpuser** [amcharts/amcharts4#3720]
**Question**

While trying to test world map using jest and react-testing-library the below error is popping up,

 TypeError: svg.createSVGMatrix is not a function
at MapPolygonSeries.Sprite.measure (node_modules/src/.internal/core/Sprite.ts:2618:32)
at MapPolygonSeries.Sprite.validatePosition (node_modules/src/.internal/core/Sprite.ts:1248:35)
 at MapPolygonSeries.Sprite.showReal (node_modules/src/.internal/core/Sprite.ts:8345:10)
at MapPolygonSeries.Sprite.show (node_modules/src/.internal/core/Sprite.ts:8319:15)
at MapPolygonSeries.Sprite.appear (node_modules/src/.internal/core/Sprite.ts:9479:25)
at Object.dispatch (node_modules/src/.internal/core/utils/EventDispatcher.ts:444:90)
at node_modules/src/.internal/core/utils/EventDispatcher.ts:346:17
 at triggerIdle (node_modules/src/.internal/core/utils/AsyncPending.ts:162:9)
at System.update (node_modules/src/.internal/core/System.ts:351:3)
 at node_modules/src/.internal/core/System.ts:405:10

**Environment**

 - amCharts version ** "@amcharts/amcharts4": "^4.10.2",**
 - Frameworks "react": "^16.11.1",

**Comment by martynasma** [comment]
amCharts 4 is not compatible with Jest, I'm afraid.

More details here: https://www.amcharts.com/docs/v4/getting-started/using-typescript-or-es6/#Using_amCharts_with_Jest
