### ISSUE TITLE
EventDispatcher is disposed 

### ISSUE THREAD

**Issue by matanswisa** [amcharts/amcharts4#3980]
I'm using amCharts version4 PolygonSeries to draw a polygon painting on a MapChart object.
When I change chrome's zoom settings an error is raise and it's saying:

```
Error: EventDispatcher is disposed
    at SpriteEventDispatcher.EventDispatcher.isEnabled (EventDispatcher.ts:228:1)
    at MapImageSeries.BaseObjectEvents.dispatch (Base.ts:1344:1)
    at MapImageSeries.Sprite.handleGlobalScale (Sprite.ts:1418:1)
    at MapImageSeries.Container.handleGlobalScale (Container.ts:819:1)
    at MapImageSeries.set [as scale] (Sprite.ts:7398:1)
    at MapChart.ts:1384:1
    at Iterator.ts:100:1
    at Iterator.ts:45:1
    at Module.each (Iterator.ts:99:1)
    at MapChart.updateScaleRatio (MapChart.ts:1383:1)
    at MapChart.ts:726:1
    at Object.dispatch (EventDispatcher.ts:444:1)
    at EventDispatcher.ts:324:1
    at Module.each (Array.ts:95:1)
    at SpriteEventDispatcher.EventDispatcher._eachListener (EventDispatcher.ts:294:1)
    at SpriteEventDispatcher.EventDispatcher.dispatchImmediately (EventDispatcher.ts:322:1)
    at MapChart.BaseObjectEvents.dispatchImmediately (Base.ts:1377:1)
    at MapChart.Sprite.setMaxWidth (Sprite.ts:6908:1)
    at MapChart.set [as maxWidth] (Sprite.ts:6890:1)
    at Container.ts:936:1
    at Module.each (Array.ts:95:1)
    at Container.validateLayout (Container.ts:900:1)
    at System.validateLayouts (System.ts:485:1)
    at System.ts:262:1
    at Object.ts:120:1
    at eachContinue (Object.ts:105:1)
    at Module.each (Object.ts:119:1)
    at System.update (System.ts:261:1)
    at System.ts:405:1
```

Additionly a pop up message appears with the content "EventDispatcher is disposed" , mapChart disappear right after i close the message.

<img width="662" alt="mapChart" src="https://user-images.githubusercontent.com/49640186/151945837-82b7148e-c66d-46f1-8e66-8393aea814bd.png">

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?
