### ISSUE TITLE
Page crash

### ISSUE THREAD

**Issue by moncy-kv** [amcharts/amcharts4#4333]
I am getting the following error when chart is being rendered and the page keeps crashing.

Error : 
```
EventDispatcher.ts:369 Uncaught Error: EventDispatcher is disposed
    at e._on (EventDispatcher.ts:369:10)
    at c._on (SpriteEvents.ts:104:25)
    at e.once (EventDispatcher.ts:487:18)
    at c.processBullet (Series.ts:601:15)
    at Object.dispatch (EventDispatcher.ts:444:90)
    at EventDispatcher.ts:324:15
    at Vle (Array.ts:95:3)
    at e._eachListener (EventDispatcher.ts:294:4)
    at e.dispatchImmediately (EventDispatcher.ts:322:9)
    at e.push [(List.ts:776:16)]
```

![image (1)](https://github.com/amcharts/amcharts4/assets/89776023/807a1362-870a-4058-85e6-09770d12d459)

Development environment:

amCharts version :4.10.32
Browser and its version : chrome
Related frameworks and their versions : ReactJS 18.2.0

**Comment by martynasma** [comment]
Would you be able to post your whole chart and data on CodePen/jsFiddle so that we can test?

**Comment by nikitha-keyvalue** [comment]
This issue doesn't occur consistently. I tried reproducing it on codepen but was not able to. Is it possible to determine what might be causing this?

**Comment by martynasma** [comment]
Not, really, I'm afraid 😒. We need a way to reproduce it to be able to take a stab at figuring it out.
