### ISSUE TITLE
Syntax error when building amCharts into package using Rollup

### ISSUE THREAD

**Issue by ianoc90** [amcharts/amcharts4#89]
I am attempting to build amcharts4 into a package using rollup.js. Mainly following this [boilerplate](https://github.com/alexjoverm/typescript-library-starter). 

I am seeing this error when I run a build.

```
[!] (commonjs plugin) SyntaxError: Unexpected token (2255:49) in C:\path\to\my\project\node_modules\@amcharts\amcharts4\.internal\core\export\Export.js
node_modules\@amcharts\amcharts4\.internal\core\export\Export.js (2255:49)
2253:             return __generator(this, function (_a) {
2254:                 switch (_a.label) {
2255:                     case 0: return [4 /*yield*/, import(/* webpackChunkName: "fabric" */ "../../fabric/fabric")];
                                                       ^
2256:                     case 1: return [2 /*return*/, _a.sent()];
2257:                 }

```

This is my rollup.config.ts
```
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import sourceMaps from 'rollup-plugin-sourcemaps'
import camelCase from 'lodash.camelcase'
import typescript from 'rollup-plugin-typescript2'
import json from 'rollup-plugin-json'

const pkg = require('./package.json')

const libraryName = 'my-charts'

export default {
  input: `src/index.ts`,
  output: [
    { file: pkg.main, name: camelCase(libraryName), format: 'umd', sourcemap: true },
    { file: pkg.module, format: 'es', sourcemap: true },
  ],
  // Indicate here external modules you don't wanna include in your bundle (i.e.: 'lodash')
  external: [],
  watch: {
    include: 'src/**',
  },
  plugins: [
    // Allow json resolution
    json(),
    // Compile TypeScript files
    typescript({ useTsconfigDeclarationDir: true }),
    
    // Allow bundling cjs modules (unlike webpack, rollup doesn't understand cjs)
    commonjs(),
    // Allow node_modules resolution, so you can use 'external' to control
    // which external modules to include in the bundle
    // https://github.com/rollup/rollup-plugin-node-resolve#usage
    resolve(),

    // Resolve source maps to the original source
    sourceMaps(),
  ],
}

```

Maybe I'm trying to process it in a way that is not supported yet, but can't seem to see what.

**Comment by ianoc90** [comment]
Interestingly enough. I'm seeing the same error in another rollup implementation. I tried following the [`rollup-starter-lib`](https://github.com/rollup/rollup-starter-lib/tree/babel) which the [rollup docs](https://rollupjs.org/guide/en#quick-start) pointed towards.

`rollup.config.js`
```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import pkg from './package.json';

export default [
  // browser-friendly UMD build
  {
    entry: 'src/index.js',
    dest: pkg.browser,
    format: 'umd',
    moduleName: 'howLongUntilLunch',
    plugins: [
      resolve(), // so Rollup can find `ms`
      commonjs(), // so Rollup can convert `ms` to an ES module
      babel({
        exclude: ['node_modules/**']
      })
    ]
  },

  // CommonJS (for Node) and ES module (for bundlers) build.
  // (We could have three entries in the configuration array
  // instead of two, but it's quicker to generate multiple
  // builds from a single configuration where possible, using
  // the `targets` option which can specify `dest` and `format`)
  {
    entry: 'src/index.js',
    external: ['ms'],
    targets: [
      { dest: pkg.main, format: 'cjs' },
      { dest: pkg.module, format: 'es' }
    ],
    plugins: [
      resolve(),
      babel({
        exclude: ['node_modules/**']
      })
    ]
  }
];
```
Logs
```
src/index.js → dist/how-long-till-lunch.umd.js...
[!] (commonjs plugin) SyntaxError: Unexpected token (2255:49) in C:\path\to\my\project\node_modules\@amcharts\amcharts4\.internal\core\export\Export.js
node_modules\@amcharts\amcharts4\.internal\core\export\Export.js (2255:49)
SyntaxError: Unexpected token (2255:49) in C:\path\to\my\project\node_modules\@amcharts\amcharts4\.internal\core\export\Export.js
    at error (C:\path\to\my\project\node_modules\rollup\dist\rollup.js:181:12)
    at C:\path\to\my\project\node_modules\rollup\dist\rollup.js:9440:6
    at <anonymous>
```

**Comment by Pauan** [comment]
Hmmm, that's odd, I just tried creating a Rollup app using V4 and it seems to work perfectly fine.

What's the version of Rollup that you are using?

Have you tried setting `experimentalCodeSplitting` and `experimentalDynamicImport` to `true` in your Rollup config?

**Comment by ianoc90** [comment]
Yep I've tried using those flags in the commonjs plugin. 

Could you show me your `rollup.config.js`?

**Comment by ianoc90** [comment]
Oh sorry.. I forgot to answer your other question. The version of rollup I have installed is `0.58.2`.

Here is my `package.json`
```
{
  "name": "my-package-json",
  "version": "0.1.0",
  "description": "",
  "keywords": [],
  "main": "dist/showtime-charts.umd.js",
  "module": "dist/showtime-charts.es5.js",
  "typings": "dist/types/showtime-charts.d.ts",
  "files": [
    "dist"
  ],
  "author": "Ian O'Connor <ianoc90@gmail.com>",
  "repository": {
    "type": "git",
    "url": ""
  },
  "license": "MIT",
  "engines": {
    "node": ">=6.0.0"
  },
  "scripts": {
    "lint": "tslint -t codeFrame 'src/**/*.ts' 'test/**/*.ts'",
    "prebuild": "rimraf dist",
    "build": "tsc --module commonjs && rollup -c rollup.config.ts && typedoc --out docs --target es6 --theme minimal --mode file src",
    "start": "rollup -c rollup.config.ts -w",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:prod": "npm run lint && npm run test -- --coverage --no-cache",
    "commit": "git-cz",
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "{src,test}/**/*.ts": [
      "prettier --write",
      "git add"
    ]
  },
  "config": {
    "commitizen": {
      "path": "node_modules/cz-conventional-changelog"
    },
    "validate-commit-msg": {
      "types": "conventional-commit-types",
      "helpMessage": "Use \"npm run commit\" instead, we use conventional-changelog format :) (https://github.com/commitizen/cz-cli)"
    }
  },
  "jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/test/"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 95,
        "lines": 95,
        "statements": 95
      }
    },
    "collectCoverage": true
  },
  "prettier": {
    "semi": false,
    "singleQuote": true
  },
  "devDependencies": {
    "@amcharts/amcharts4": "^4.0.0-beta.29",
    "@types/jest": "^22.0.0",
    "@types/node": "^10.0.3",
    "colors": "^1.1.2",
    "commitizen": "^2.9.6",
    "coveralls": "^3.0.0",
    "cross-env": "^5.0.1",
    "cz-conventional-changelog": "^2.0.0",
    "husky": "^0.14.0",
    "jest": "^22.0.2",
    "lint-staged": "^7.0.0",
    "lodash.camelcase": "^4.3.0",
    "prettier": "^1.4.4",
    "prompt": "^1.0.0",
    "replace-in-file": "^3.0.0-beta.2",
    "rimraf": "^2.6.1",
    "rollup": "^0.58.0",
    "rollup-plugin-babel": "^3.0.4",
    "rollup-plugin-commonjs": "^9.0.0",
    "rollup-plugin-json": "^3.0.0",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "rollup-plugin-typescript2": "^0.11.1",
    "ts-jest": "^22.0.0",
    "ts-node": "^6.0.0",
    "tslint": "^5.8.0",
    "tslint-config-prettier": "^1.1.0",
    "tslint-config-standard": "^7.0.0",
    "typedoc": "^0.11.0",
    "typescript": "^2.6.2",
    "validate-commit-msg": "^2.12.2"
  }
}

```

**Comment by Pauan** [comment]
Here is the configuration that I tested:

https://gist.github.com/Pauan/4b5fa58d64fce118dcd3581557e6012e

It is using Rollup version `0.61.2`, perhaps you just need to upgrade to the latest version?

**Comment by ianoc90** [comment]
That seems to solve the syntax error 👍
